<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2ASADG1" ignored="1" name="Command line test" tests="19" failures="1" timestamp="05 Feb 2022 12:23:50 GMT" time="58.651" errors="0">
  <testcase name="tc10" time="0.0" classname="org.testng1.Testng"/>
  <testcase name="test4" time="0.0" classname="org.testng.Testng2"/>
  <testcase name="test5" time="0.0" classname="org.testng.Testng2"/>
  <testcase name="test6" time="0.0" classname="org.testng.Testng2"/>
  <testcase name="test8" time="0.0" classname="org.testng.Testng3"/>
  <testcase name="test7" time="0.0" classname="org.testng.Testng3"/>
  <testcase name="test9" time="0.0" classname="org.testng.Testng3"/>
  <testcase name="tc10" time="0.0" classname="org.testng.Testing"/>
  <testcase name="tc9" time="0.0" classname="org.testng.Testing"/>
  <testcase name="test1" time="0.0" classname="org.testng.Testng1"/>
  <testcase name="test2" time="0.0" classname="org.testng.Testng1"/>
  <testcase name="test3" time="0.0" classname="org.testng.Testng1"/>
  <testcase name="tc1" time="30.254" classname="org.parallelexecution.Test1"/>
  <testcase name="tc2" time="8.27" classname="org.parallelexecution.Test1"/>
  <testcase name="tc1" time="0.0" classname="org.Rerun.TestngRerun"/>
  <testcase name="tc2" time="0.003" classname="org.Rerun.TestngRerun">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.Rerun.TestngRerun.tc2(TestngRerun.java:14)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.Rerun.TestngRerun"/>
  <testcase name="tc1" time="10.751" classname="org.parallelexecution.Test2"/>
  <testcase name="tc2" time="9.331" classname="org.parallelexecution.Test2"/>
  <testcase name="tc9" time="0.0" classname="org.testng1.Testng">
    <ignored/>
  </testcase> <!-- tc9 -->
</testsuite> <!-- Command line test -->
